services:
  sudp-server:
    build:
      context: ..
      dockerfile: e2e/containers/http-server/Dockerfile
    container_name: sudp-server
    cap_add:
      - NET_ADMIN
    environment:
      SERVER_ADDRESS: ":80"

      DELAY: ${NET_SERVER_DELAY:-10ms}
      LOSS: ${NET_SERVER_LOSS:-0.1%}

      CLIENTS_COUNT: ${CLIENTS_COUNT:-100}
    command: ["/netem.sh", "/app/cmd"]
    networks:
      - testnet

  sudp-client:
    build:
      context: ..
      dockerfile: e2e/containers/http-client/Dockerfile
    depends_on:
      - sudp-server
    cap_add:
      - NET_ADMIN
    environment:
      SERVER_ADDRESS: "sudp-server:80"

      DELAY: ${NET_CLIENT_DELAY:-10ms}
      LOSS: ${NET_CLIENT_LOSS:-0.1%}
    command: ["/netem.sh", "/app/cmd"]
    networks:
      - testnet
    deploy:
      replicas: ${CLIENTS_COUNT:-100}


networks:
  testnet:
    driver: bridge